# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'authtest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for authtest
  pod 'SVProgressHUD'
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'TwitterCore'

  target 'authtestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'authtestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

plugin 'cocoapods-keys', {
  :project => "AuthTest",
  :keys => [
    "consumerKey",
    "secretKey"
  ]}
